# CONTRASTES DE HIPÓTESIS

Máster: Data Science y Business Analytics

Módulo: Estadística para Científicos de Datos

Profesora: Paloma Fontanillo Rodrigo

## Importamos las librerías necesarias

In [2]:
import numpy as np
import random
np.random.seed(5)

from scipy.stats import norm
from scipy.stats import expon
from scipy.stats import uniform

from scipy.stats import ttest_1samp

from scipy.stats import ttest_ind

from scipy.stats import shapiro
from scipy.stats import normaltest

from scipy.stats import kstest
from scipy.stats import ks_2samp

from scipy.stats import levene

import numpy as np

## EJERCICIO 1

###### ●Genera una muestra de 300 observaciones de una normal con media 27 y desviación típica 4 - Muestra_A

In [4]:
x = norm.rvs(loc=27, scale=4, size=300)
x

array([28.70865608, 37.35427834, 29.61157206, 29.02335917, 25.09619668,
       31.04363496, 32.43680388, 20.19164013, 21.47867108, 35.40710673,
       28.70359667, 27.51680092, 29.25185005, 31.3870589 , 30.2032754 ,
       26.10766693, 35.25468266, 27.05049401, 23.50090481, 24.77168248,
       26.4707922 , 25.48310006, 26.24882518, 28.2618646 , 13.86433821,
       23.88522699, 30.80137883, 29.25200521, 24.27738374, 24.50198644,
       31.56198375, 26.00908423, 24.8791789 , 34.42285762, 25.52051149,
       29.73698726, 26.81731881, 27.2031466 , 23.21109778, 23.69205033,
       32.03229443, 22.44443897, 28.10944047, 22.22221614, 26.03825266,
       26.85116694, 20.4812864 , 31.5394535 , 26.26480227, 31.85895091,
       23.26288562, 30.64744965, 36.33696038, 27.86612782, 24.41172609,
       28.91482422, 27.56330861, 26.1600056 , 26.51797342, 24.68469687,
       28.69547037, 25.45067455, 23.57252741, 30.26125557, 26.33673593,
       37.58141378, 26.00212049, 24.13064842, 24.80201067, 28.48

###### ►Comprueba con un test de hipótesis si la muestra tiene media 0

In [5]:
ttest_1samp(x, popmean=0)
#La media es 0

TtestResult(statistic=117.0497361541034, pvalue=8.645007222771151e-252, df=299)

###### Escribe cual es la hipótesis nula y cual es la alternativa
La hipotésis nula es cuando la media es igual 0 y la hipotésis alternativa es cuando la media es diferente de 0

###### Interpreta el p-valor
El p valor del presente ejercicio es pequeño porque es mayor a 0,1, entonces H0 se rechaza

###### ►Comprueba con un test de hipótesis si la muestra tiene media menor que 0

In [6]:
ttest_1samp(x, popmean=0,  alternative='less')
#Como es mayor a 0.1 se acepta

TtestResult(statistic=117.0497361541034, pvalue=1.0, df=299)

###### Escribe cual es la hipótesis nula y cual es la alternativa
La hipotésis nula es cuando la media es igual 0 y la hipotésis alternativa es cuando la media es diferente de 0

###### Interpreta el p-valor
El p valor del presente ejercicio de que la media sea menor a 0 es 1.0, por lo tanto se acepta

###### ►Comprueba con un test de hipótesis si la muestra tiene media mayor que 0

In [7]:
ttest_1samp(x, popmean=0,  alternative='greater')

TtestResult(statistic=117.0497361541034, pvalue=4.3225036113855757e-252, df=299)

###### Escribe cual es la hipótesis nula y cual es la alternativa
La hipotésis nula es cuando la media es igual 0 y la hipotésis alternativa es cuando la media es diferente de 0

###### Interpreta el p-valor
el p valor tiene un valor menor a 0, por lo tanto se rechaza porque este no es mayor a 0

###### ►Comprueba con un test de hipótesis si la muestra tiene media 27

In [8]:
ttest_1samp(x, popmean=27)

TtestResult(statistic=0.4634157156015352, pvalue=0.6434035608690118, df=299)

In [ ]:
# En el punto anterior se puede comprobar que la media no puede ser 27, porque el pvalue es mayor a 0.1

###### Escribe cual es la hipótesis nula y cual es la alternativa
La hipotésis nula es cuando la media es igual 0 y la hipotésis alternativa es cuando la media es diferente de 0

###### Interpreta el p-valor
En el punto anterior se puede comprobar que la media no puede ser 27, porque el pvalue es mayor a 0.1

## EJERCICIO 2

###### ●Genera una muestra de 300 observaciones de una normal con media 340 y desviación típica 15 - Muestra_B

In [10]:
y = norm.rvs(loc=340, scale=15, size=300)
y

array([315.309828  , 313.09510576, 325.3099204 , 324.84087711,
       330.83372946, 324.10306171, 337.95515035, 331.03699322,
       343.09725788, 340.05097366, 349.00293188, 325.5885004 ,
       326.70145589, 323.3297687 , 341.40815299, 351.00978124,
       357.38822466, 342.56287804, 337.96671249, 351.17154188,
       339.30735302, 325.02126548, 351.20747778, 333.72917614,
       317.82439768, 337.23776013, 327.59093541, 339.42346439,
       329.20689198, 335.13069963, 330.88401586, 338.16468208,
       348.62505157, 343.65189256, 339.98624341, 355.33655089,
       319.5727612 , 342.4979092 , 357.54627303, 348.392203  ,
       356.87045491, 326.10603311, 357.18957946, 329.48313045,
       356.95257009, 343.81395122, 352.896546  , 328.28871702,
       336.77370018, 312.41862329, 345.47362811, 351.24201424,
       345.77531572, 357.25001695, 349.53759866, 342.48112875,
       348.89707109, 332.45670499, 354.53349432, 344.82522041,
       345.74097438, 338.70097783, 332.10238002, 326.56

###### ●Genera una muestra de 300 observaciones de una normal con media 220 y desviación típica 15 - Muestra_C

In [12]:
z = norm.rvs(loc=220, scale=15, size=300)
z


array([210.00203393, 210.23569033, 187.26625129, 216.29263474,
       214.23893324, 226.98289017, 209.64574355, 213.48329486,
       213.94011296, 211.92831096, 215.23516455, 210.92145266,
       237.25250823, 217.32347395, 225.46678217, 224.91687242,
       203.9558961 , 189.59751254, 202.18436383, 214.0106812 ,
       219.27982184, 198.68644074, 228.67426932, 214.06902116,
       231.24268421, 205.17417192, 176.18945574, 227.13327088,
       225.85895251, 252.66796984, 220.30318498, 223.60015194,
       244.94119629, 177.66651006, 197.24489295, 189.73804904,
       223.86180909, 214.91801083, 226.55797393, 194.9090204 ,
       207.42129108, 217.64337388, 215.29209845, 213.54995844,
       233.61857866, 207.00458575, 210.5803021 , 210.19074765,
       227.07808595, 202.23607188, 202.03723134, 203.01850885,
       192.81954877, 214.07207099, 207.45529821, 186.1728951 ,
       208.72709157, 217.60565185, 240.49385807, 215.38250939,
       237.20092943, 219.86031908, 236.83607337, 198.82

###### ►Comprueba con un test de hipótesis si las dos muestras tienen distinta media

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

## EJERCICIO 3

###### ●Genera una muestra de 300 observaciones de una normal con media 340 y desviación típica 15 - Muestra_D

###### ●Genera una muestra de 300 observaciones de una normal con media 220 y desviación típica 5 - Muestra_E

###### ●Genera una muestra de 300 observaciones de una normal con media 340 y desviación típica 5 - Muestra_F

###### ►Comprueba con un test de hipótesis si las muestras D y E tienen distinta media

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

###### ►Comprueba con un test de hipótesis si las muestras D y F tienen distinta media

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

## EJERCICIO 4

###### ●Genera una muestra de 4000 observaciones de una normal con media 72 y desviación típica 10 - Muestra_G

###### ●Genera una muestra de 4000 observaciones de una exponencial de parámetro 50 - Muestra_H

###### ►Comprueba con un test de hipótesis si la muestra_G es normal

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

###### ►Comprueba con un test de hipótesis si la muestra_H es normal

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

## EJERCICIO 5

###### ●Genera una muestra de 3000 observaciones de una normal con media 340 y desviación típica 150 - Muestra_I

###### ●Genera una muestra de 3000 observaciones de una normal con media 340 y desviación típica 150 - Muestra_J

###### ●Genera una muestra de 3000 observaciones de una uniforme entre 0 y 800 - Muestra_K

###### ●Genera una muestra de 3000 observaciones de una uniforme entre 0 y 800 - Muestra_L

###### ►Comprueba con un test de hipótesis si las muestras I y J tienen la misma distribución

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

###### ►Comprueba con un test de hipótesis si las muestras I y K tienen la misma distribución

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

###### ►Comprueba con un test de hipótesis si las muestras K y L tienen la misma distribución

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

## EJERCICIO 6

###### ●Genera una muestra de 200 observaciones de una normal con media 280 y desviación típica 80 - Muestra_M

###### ►Comprueba con un test de hipótesis si la muestra M se distribuye como una normal(280, 80)

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

###### ►Comprueba con un test de hipótesis si la muestra M se distribuye como una uniforme(100, 200)

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

## EJERCICIO 7

###### ●Genera una muestra de 40 observaciones de una uniforme(10,50) - Muestra_N

###### ►Comprueba con un test de hipótesis si la muestra N se distribuye como una uniforme(10, 50)

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

###### ►Comprueba con un test de hipótesis si la muestra N se distribuye como una normal(20, 4)

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor

###### ►Comprueba con un test de hipótesis si la muestra N se distribuye como una normal(30, 0)

###### Escribe cual es la hipótesis nula y cual es la alternativa

###### Interpreta el p-valor